---
- hosts: localhost
  connection: local
  vars:
    user: "nathan"
    home: "/home/{{ user }}"
    dotfiles: "{{ home }}/dotfiles"
    xdg_config_home: "{{ home }}/.config"
    bindir: "{{ home }}/bin"
  roles:
    - common
    - zsh
    - xresources
    - ranger
    - mutt
    - systemd
