---
- name: zshenv
  template: src="zshenv" dest="/home/{{ user }}/.zshenv" owner="{{ user }}"

- name: zshrc
  template: src="zshrc" dest="/home/{{ user }}/.zshrc" owner="{{ user }}"

- name: zsh config files
  template: src="{{ item }}" dest="{{ xdg_config_home }}/zsh/" owner="{{ user }}"
  with_fileglob: 'zsh-config/*'
